services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    command: ["./cloudrun"]

  test:
    build:
      context: .
      target: builder # Use a etapa "builder" que contém o Go
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "test", "./...", "-v", "-cover"]

